--Asian Population
SELECT SUM(CITY.POPULATION)
FROM CITY INNER JOIN COUNTRY ON COUNTRY.CODE = CITY.COUNTRYCODE
WHERE COUNTRY.CONTINENT = 'Asia'

--当然方法不止一种哦， 不用join也能做
SELECT SUM(COUNTRY.POPULATION)
FROM CITY, COUNTRY
WHERE COUNTRY.CONTINENT = 'Asia'
AND COUNTRY.CODE = CITY.COUNTRYCODE

